name: auto-release
on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  auto-release:
    uses: alpine-ros/alpine-ros-ci-workflows/.github/workflows/auto-release.yaml@main
    secrets:
      token: ${{ secrets.BLOOM_GITHUB_TOKEN }}
